syntax = "proto3";

option csharp_namespace = "WebShop.BasketAPI";

package basket;

// The basket service definition.
service Basket {

  // Adds an item to the basket
  rpc GetBasket (GetBasketRequest) returns (BasketResponse);
  rpc UpdateBasket (UpdateBasketRequest) returns (BasketResponse); 
  rpc RemoveBasket (RemoveBasketRequest) returns (RemoveBasketResponse);
}

message GetBasketRequest { }

message UpdateBasketRequest {
  repeated BasketItem Items = 2;
}

message RemoveBasketRequest { }
message RemoveBasketResponse { }

message BasketResponse {
  repeated BasketItem Items = 2;
}

message BasketItem {
  int32  ProductId = 1;
  int32  Quantity = 2;
}

